#!/bin/sh -e
# Public domain.

umask 022
test -d package -a -d src -a -d conf-compile || { echo 'Wrong working directory.' ; exit 100 ; }

test -n "$1" || ( echo "crosscompile: usage: crosscompile sysdepdir" ; exit 100 )
test -d "$1" || ( echo "crosscompile: usage: crosscompile sysdepdir" ; exit 100 )

package/prepare
package/crossconfigure "$1"
package/make
package/makeinstall

:> .done
